#!/usr/bin/env python3
"""Build a self-contained, compilable copy of a module that has a small
external surface, so its tests can run without cargo or the registry.

The point is fidelity. Protocol types are **extracted from the real source**
rather than hand-written, so a stub can never silently drift from the type it
is standing in for — if a field is added to `InputKind`, the harness picks it
up and the module either still compiles or genuinely broke. Only functions that
touch the OS (input injection, clipboard) are replaced with no-ops, plus
`anyhow::Result` and the `tracing` macros.

What this does NOT verify: anything those stubbed functions actually do. It
checks the module's own logic and that it type-checks against the real
protocol types. See scripts/verify-offline.sh for the wider caveats.

Usage:
  offline_harness.py --module <path.rs> --out <path.rs> \
      [--types <src.rs>:<Name>,<Name>...]
"""

import argparse
import re
import sys


def extract_item(src: str, name: str) -> str:
    """Return the `pub struct`/`pub enum` block named `name`, minus attributes."""
    m = re.search(rf"^pub (?:struct|enum) {re.escape(name)}\b", src, re.M)
    if not m:
        sys.exit(f"offline_harness: type not found in source: {name}")
    start = m.start()
    i = src.index("{", start)
    depth = 0
    while True:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    body = src[start : i + 1]
    keep = [
        ln
        for ln in body.split("\n")
        if not ln.strip().startswith("#[") and not ln.strip().startswith("///")
    ]
    return "\n".join(keep)


HARNESS_TMPL = """// GENERATED by scripts/offline_harness.py — do not edit.
// Protocol types below are extracted verbatim from the real source, so they
// cannot drift. Only OS-touching functions are stubbed.
#[allow(unused)]
mod anyhow {{
    pub type Result<T = ()> = std::result::Result<T, Box<dyn std::error::Error>>;
}}

// Named with a suffix: a bare `warn` macro collides with the built-in lint attribute.
macro_rules! log_noop {{ ($($t:tt)*) => {{}} }}
mod tracing {{
    pub(crate) use log_noop as debug;
    pub(crate) use log_noop as warn;
}}

mod miru_common {{
    pub mod message {{
{types}
    }}
}}

#[allow(unused)]
mod miru_input {{
    use super::miru_common::message::InputEvent;
    pub fn inject(_e: &InputEvent) -> super::anyhow::Result {{ Ok(()) }}
    pub fn set_clipboard(_t: &str) -> super::anyhow::Result {{ Ok(()) }}
    pub fn set_clipboard_raw(_d: &[u8], _m: &str) -> super::anyhow::Result {{ Ok(()) }}
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument(
        "--types",
        required=True,
        help="<source.rs>:<TypeA>,<TypeB> — types to extract verbatim",
    )
    args = ap.parse_args()

    type_src_path, names = args.types.split(":", 1)
    with open(type_src_path) as f:
        type_src = f.read()
    types = "\n\n".join(extract_item(type_src, n.strip()) for n in names.split(","))

    harness = HARNESS_TMPL.format(types=types)

    with open(args.module) as f:
        lines = f.read().split("\n")
    # Inner doc comments (//!) must remain the first thing in the file, so the
    # harness is spliced in after them.
    i = 0
    while i < len(lines) and (lines[i].startswith("//!") or lines[i].strip() == ""):
        i += 1
    with open(args.out, "w") as f:
        f.write("\n".join(lines[:i]) + "\n" + harness + "\n".join(lines[i:]))


if __name__ == "__main__":
    main()
