#!/usr/bin/env python3
"""Build a self-contained, compilable copy of a module that has a small
external surface, so its tests can run without cargo or the registry.

The point is fidelity. Protocol types are **extracted from the real source**
rather than hand-written, so a stub can never silently drift from the type it
is standing in for — if a field is added to `InputKind`, the harness picks it
up and the module either still compiles or genuinely broke. The only edit made
to an extracted type is dropping the derives and attributes that need an
external crate (Serialize/Deserialize, serde attrs); every compiler-derivable
trait is kept, since dropping e.g. PartialEq would change what the module can
do. Beyond that, only functions that touch the OS (input injection, clipboard)
are replaced with no-ops, plus `anyhow` and the `tracing` macros.

What this does NOT verify: anything those stubbed functions actually do. It
checks the module's own logic and that it type-checks against the real
protocol types. See scripts/verify-offline.sh for the wider caveats.

Usage:
  offline_harness.py --module <path.rs> --out <path.rs> \
      [--types <src.rs>:<Name>,<Name>...]
"""

import argparse
import re
import sys


# Traits derivable by the compiler alone. Serialize/Deserialize need the serde
# crate, so they are dropped — nothing here tests wire encoding. Everything else
# is kept, because dropping e.g. PartialEq changes what the module can do.
STD_DERIVES = {
    "Debug", "Clone", "Copy", "PartialEq", "Eq", "PartialOrd", "Ord", "Hash", "Default",
}


def rewrite_attrs(body: str) -> str:
    """Keep compiler-derivable traits; drop doc comments and all other attributes."""
    out = []
    for ln in body.split("\n"):
        s = ln.strip()
        if s.startswith("///") or s.startswith("//!"):
            continue
        if s.startswith("#["):
            d = re.fullmatch(r"#\[derive\(([^)]*)\)\]", s)
            if not d:
                continue  # serde attrs, repr, non_exhaustive, …
            kept = [t.strip() for t in d.group(1).split(",") if t.strip() in STD_DERIVES]
            if kept:
                out.append(ln[: len(ln) - len(s)] + f"#[derive({', '.join(kept)})]")
            continue
        out.append(ln)
    return "\n".join(out)


def _block_end(src: str, brace_at: int) -> int:
    """Index just past the `}` closing the block whose `{` is at brace_at."""
    i, depth = brace_at, 0
    while True:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1


def extract_inherent_impls(src: str, name: str) -> list:
    """Return `impl <Name> { ... }` blocks — a type without its own methods is
    not the type. Trait impls are deliberately skipped: they may reference
    traits from crates that are not present here."""
    out = []
    for m in re.finditer(rf"^impl\s+{re.escape(name)}\s*\{{", src, re.M):
        out.append(rewrite_attrs(src[m.start() : _block_end(src, m.end() - 1)]))
    return out


def extract_item(src: str, name: str) -> str:
    """Return the `pub struct`/`pub enum`/`pub trait` block named `name`."""
    m = re.search(rf"^pub (?:struct|enum|trait) {re.escape(name)}\b", src, re.M)
    if not m:
        sys.exit(f"offline_harness: type not found in source: {name}")
    # Walk back over the attribute/doc lines attached above the item so the
    # #[derive(...)] block comes along with it.
    start = m.start()
    while start > 0:
        prev = src.rindex("\n", 0, start - 1) + 1 if start > 1 else 0
        if not src[prev:start].lstrip().startswith(("#[", "///")):
            break
        start = prev
    end = _block_end(src, src.index("{", m.start()))
    return rewrite_attrs(src[start:end])


HARNESS_TMPL = """// GENERATED by scripts/offline_harness.py — do not edit.
// Protocol types below are extracted from the real source, so they cannot
// drift. Only OS-touching functions and crate-dependent derives are stubbed.
// `bail` is defined at crate root because macro_rules! is textually scoped;
// `anyhow::bail` then re-exports it so `use anyhow::bail;` resolves.
macro_rules! anyhow_err {{ ($($t:tt)*) => {{ Into::<Box<dyn std::error::Error>>::into(format!($($t)*)) }} }}
macro_rules! bail {{ ($($t:tt)*) => {{ return Err(anyhow_err!($($t)*)) }} }}

#[allow(unused)]
mod anyhow {{
    // Two parameters with defaults, so both `Result<T>` and `Result<T, E>`
    // resolve — extracted traits use either form.
    pub type Result<T = (), E = Box<dyn std::error::Error>> = std::result::Result<T, E>;
    pub type Error = Box<dyn std::error::Error>;
    pub(crate) use anyhow_err as anyhow;
    pub(crate) use bail;
    /// Stub of anyhow's Context: preserves the Ok/Err decision, drops the message.
    pub trait Context<T> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T>;
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T>;
    }}
    impl<T, E: std::fmt::Display> Context<T> for std::result::Result<T, E> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T> {{
            self.map_err(|e| format!("{{c}}: {{e}}").into())
        }}
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T> {{
            self.map_err(|e| format!("{{}}: {{e}}", f()).into())
        }}
    }}
    impl<T> Context<T> for Option<T> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T> {{
            self.ok_or_else(|| c.to_string().into())
        }}
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T> {{
            self.ok_or_else(|| f().to_string().into())
        }}
    }}
}}

// Named with a suffix: a bare `warn` macro collides with the built-in lint attribute.
macro_rules! log_noop {{ ($($t:tt)*) => {{}} }}
mod tracing {{
    pub(crate) use log_noop as trace;
    pub(crate) use log_noop as debug;
    pub(crate) use log_noop as info;
    pub(crate) use log_noop as warn;
    pub(crate) use log_noop as error;
}}

// Reachable both as `crate::message::X` (for modules that live inside
// miru-common) and as `miru_common::message::X` (for modules in other crates).
pub mod message {{
    // Extracted traits may return `Result<T>` in anyhow's one-parameter form.
    #[allow(unused_imports)]
    use super::anyhow::Result;
{types}
}}
mod miru_common {{
    pub(crate) use super::message;
}}
// Extracted types are also visible at the crate root, for modules that refer to
// their own crate's items as `crate::Thing`.
#[allow(unused_imports)]
pub use message::*;
{alias_mods}{input_stub}"""

# A module that says `crate::encoder::EncoderBackend` needs an `encoder` module
# to exist. Rather than model the real module tree, every alias re-exports the
# whole extracted set — enough to resolve the path, and it cannot invent a type
# that was not extracted from real source.
ALIAS_TMPL = """
#[allow(unused_imports)]
pub mod %s {
    pub use super::message::*;
}
"""

# Only emitted when InputEvent is among the extracted types — a module that
# never touches input injection should not carry a stub that references it.
INPUT_STUB = """
#[allow(unused)]
mod miru_input {
    use super::miru_common::message::InputEvent;
    pub fn inject(_e: &InputEvent) -> super::anyhow::Result { Ok(()) }
    pub fn set_clipboard(_t: &str) -> super::anyhow::Result { Ok(()) }
    pub fn set_clipboard_raw(_d: &[u8], _m: &str) -> super::anyhow::Result { Ok(()) }
}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument(
        "--types",
        action="append",
        default=[],
        help="<source.rs>:<TypeA>,<TypeB> — types to extract verbatim. "
        "Repeatable, to pull types from more than one file. "
        "Omit for a module that needs only the anyhow/tracing stubs.",
    )
    ap.add_argument(
        "--prelude",
        action="append",
        default=[],
        help="File of extra Rust spliced in before the module — for stubbing a "
        "sibling module the harness cannot synthesise from a type list.",
    )
    ap.add_argument(
        "--alias",
        action="append",
        default=[],
        help="Name of a sibling module to synthesise (e.g. --alias encoder), for "
        "modules that reference their own crate as crate::<mod>::Type.",
    )
    args = ap.parse_args()

    wanted, blocks = [], []
    for spec in args.types:
        if not spec:
            continue
        type_src_path, names = spec.split(":", 1)
        with open(type_src_path) as f:
            type_src = f.read()
        for n in names.split(","):
            n = n.strip()
            wanted.append(n)
            blocks.append(extract_item(type_src, n))
            blocks.extend(extract_inherent_impls(type_src, n))
    types = "\n\n".join(blocks)

    harness = HARNESS_TMPL.format(
        types=types,
        alias_mods="".join(ALIAS_TMPL % a for a in args.alias),
        input_stub=INPUT_STUB if "InputEvent" in wanted else "",
    )
    for pre in args.prelude:
        with open(pre) as f:
            harness += "\n" + f.read()

    with open(args.module) as f:
        lines = f.read().split("\n")
    # Inner doc comments and inner attributes must remain the first thing in the
    # file, so the harness is spliced in after them. A leading `#![cfg(...)]` is
    # dropped: it exists to exclude the file from ordinary builds, which is the
    # very reason it is worth compiling here.
    head, i = [], 0
    while i < len(lines):
        ln = lines[i].strip()
        if ln.startswith("#![cfg("):
            head.append("// harness: dropped " + ln)
        elif ln.startswith("//!") or ln.startswith("#![") or ln == "":
            head.append(lines[i])
        else:
            break
        i += 1
    lines = head + lines[i:]
    i = len(head)
    with open(args.out, "w") as f:
        f.write("\n".join(lines[:i]) + "\n" + harness + "\n".join(lines[i:]))


if __name__ == "__main__":
    main()
