#!/usr/bin/env python3
"""Build a self-contained, compilable copy of a module that has a small
external surface, so its tests can run without cargo or the registry.

The point is fidelity. Protocol types are **extracted from the real source**
rather than hand-written, so a stub can never silently drift from the type it
is standing in for — if a field is added to `InputKind`, the harness picks it
up and the module either still compiles or genuinely broke. The only edit made
to an extracted type is dropping the derives and attributes that need an
external crate (Serialize/Deserialize, serde attrs); every compiler-derivable
trait is kept, since dropping e.g. PartialEq would change what the module can
do. Beyond that, only functions that touch the OS (input injection, clipboard)
are replaced with no-ops, plus `anyhow` and the `tracing` macros.

What this does NOT verify: anything those stubbed functions actually do. It
checks the module's own logic and that it type-checks against the real
protocol types. See scripts/verify-offline.sh for the wider caveats.

Usage:
  offline_harness.py --module <path.rs> --out <path.rs> \
      [--types <src.rs>:<Name>,<Name>...]
"""

import argparse
import re
import sys


# Traits derivable by the compiler alone. Serialize/Deserialize need the serde
# crate, so they are dropped — nothing here tests wire encoding. Everything else
# is kept, because dropping e.g. PartialEq changes what the module can do.
STD_DERIVES = {
    "Debug", "Clone", "Copy", "PartialEq", "Eq", "PartialOrd", "Ord", "Hash", "Default",
}


def rewrite_attrs(body: str) -> str:
    """Keep compiler-derivable traits; drop doc comments and all other attributes."""
    out = []
    for ln in body.split("\n"):
        s = ln.strip()
        if s.startswith("///") or s.startswith("//!"):
            continue
        if s.startswith("#["):
            d = re.fullmatch(r"#\[derive\(([^)]*)\)\]", s)
            if not d:
                continue  # serde attrs, repr, non_exhaustive, …
            kept = [t.strip() for t in d.group(1).split(",") if t.strip() in STD_DERIVES]
            if kept:
                out.append(ln[: len(ln) - len(s)] + f"#[derive({', '.join(kept)})]")
            continue
        out.append(ln)
    return "\n".join(out)


def extract_item(src: str, name: str) -> str:
    """Return the `pub struct`/`pub enum` block named `name`, attributes rewritten."""
    m = re.search(rf"^pub (?:struct|enum) {re.escape(name)}\b", src, re.M)
    if not m:
        sys.exit(f"offline_harness: type not found in source: {name}")
    # Walk back over the attribute/doc lines attached above the item so the
    # #[derive(...)] block comes along with it.
    start = m.start()
    while start > 0:
        prev = src.rindex("\n", 0, start - 1) + 1 if start > 1 else 0
        if not src[prev:start].lstrip().startswith(("#[", "///")):
            break
        start = prev
    i = src.index("{", m.start())
    depth = 0
    while True:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return rewrite_attrs(src[start : i + 1])


HARNESS_TMPL = """// GENERATED by scripts/offline_harness.py — do not edit.
// Protocol types below are extracted from the real source, so they cannot
// drift. Only OS-touching functions and crate-dependent derives are stubbed.
// `bail` is defined at crate root because macro_rules! is textually scoped;
// `anyhow::bail` then re-exports it so `use anyhow::bail;` resolves.
macro_rules! anyhow_err {{ ($($t:tt)*) => {{ Into::<Box<dyn std::error::Error>>::into(format!($($t)*)) }} }}
macro_rules! bail {{ ($($t:tt)*) => {{ return Err(anyhow_err!($($t)*)) }} }}

#[allow(unused)]
mod anyhow {{
    pub type Result<T = ()> = std::result::Result<T, Box<dyn std::error::Error>>;
    pub type Error = Box<dyn std::error::Error>;
    pub(crate) use anyhow_err as anyhow;
    pub(crate) use bail;
    /// Stub of anyhow's Context: preserves the Ok/Err decision, drops the message.
    pub trait Context<T> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T>;
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T>;
    }}
    impl<T, E: std::fmt::Display> Context<T> for std::result::Result<T, E> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T> {{
            self.map_err(|e| format!("{{c}}: {{e}}").into())
        }}
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T> {{
            self.map_err(|e| format!("{{}}: {{e}}", f()).into())
        }}
    }}
    impl<T> Context<T> for Option<T> {{
        fn context<C: std::fmt::Display>(self, c: C) -> Result<T> {{
            self.ok_or_else(|| c.to_string().into())
        }}
        fn with_context<C: std::fmt::Display, F: FnOnce() -> C>(self, f: F) -> Result<T> {{
            self.ok_or_else(|| f().to_string().into())
        }}
    }}
}}

// Named with a suffix: a bare `warn` macro collides with the built-in lint attribute.
macro_rules! log_noop {{ ($($t:tt)*) => {{}} }}
mod tracing {{
    pub(crate) use log_noop as trace;
    pub(crate) use log_noop as debug;
    pub(crate) use log_noop as info;
    pub(crate) use log_noop as warn;
    pub(crate) use log_noop as error;
}}

// Reachable both as `crate::message::X` (for modules that live inside
// miru-common) and as `miru_common::message::X` (for modules in other crates).
pub mod message {{
{types}
}}
mod miru_common {{
    pub(crate) use super::message;
}}
{input_stub}"""

# Only emitted when InputEvent is among the extracted types — a module that
# never touches input injection should not carry a stub that references it.
INPUT_STUB = """
#[allow(unused)]
mod miru_input {
    use super::miru_common::message::InputEvent;
    pub fn inject(_e: &InputEvent) -> super::anyhow::Result { Ok(()) }
    pub fn set_clipboard(_t: &str) -> super::anyhow::Result { Ok(()) }
    pub fn set_clipboard_raw(_d: &[u8], _m: &str) -> super::anyhow::Result { Ok(()) }
}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument(
        "--types",
        default="",
        help="<source.rs>:<TypeA>,<TypeB> — types to extract verbatim. "
        "Omit for a module that needs only the anyhow/tracing stubs.",
    )
    args = ap.parse_args()

    wanted = []
    types = ""
    if args.types:
        type_src_path, names = args.types.split(":", 1)
        with open(type_src_path) as f:
            type_src = f.read()
        wanted = [n.strip() for n in names.split(",")]
        types = "\n\n".join(extract_item(type_src, n) for n in wanted)

    harness = HARNESS_TMPL.format(
        types=types, input_stub=INPUT_STUB if "InputEvent" in wanted else ""
    )

    with open(args.module) as f:
        lines = f.read().split("\n")
    # Inner doc comments (//!) must remain the first thing in the file, so the
    # harness is spliced in after them.
    i = 0
    while i < len(lines) and (lines[i].startswith("//!") or lines[i].strip() == ""):
        i += 1
    with open(args.out, "w") as f:
        f.write("\n".join(lines[:i]) + "\n" + harness + "\n".join(lines[i:]))


if __name__ == "__main__":
    main()
